# -*- coding: utf-8 -*-
"""pca project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMAVrY5JfIlrG2SklpjI50srzT0RfCc7
"""

!pip install cupy-cuda11x opencv-python matplotlib

from google.colab import files
uploaded = files.upload()

!pip uninstall -y cupy-cuda11x cupy-cuda12x
!pip install cupy-cuda12x

import cv2
import cupy as cp
import numpy as np
import matplotlib.pyplot as plt
import time
from cupyx.scipy.ndimage import convolve

# Load image
img = cv2.imread('Eagle.jpg', cv2.IMREAD_GRAYSCALE)

# ---------------- CPU BLUR ----------------
start = time.time()
cpu_blur = cv2.blur(img, (3,3))
cpu_time = time.time() - start

# ---------------- GPU BLUR ----------------
gpu_img = cp.asarray(img)

kernel = cp.ones((3,3)) / 9

start = time.time()
gpu_blur = convolve(gpu_img, kernel)   # ✅ TRUE GPU PARALLEL
cp.cuda.Stream.null.synchronize()
gpu_time = time.time() - start

gpu_blur_cpu = cp.asnumpy(gpu_blur)

# Save output
cv2.imwrite('output_blur.jpg', gpu_blur_cpu)

# ---------------- DISPLAY ----------------
print(f"CPU Time: {cpu_time:.6f} sec")
print(f"GPU Time: {gpu_time:.6f} sec")

plt.subplot(1,2,1)
plt.title("Original")
plt.imshow(img, cmap='gray')

plt.subplot(1,2,2)
plt.title("GPU Blur")
plt.imshow(gpu_blur_cpu, cmap='gray')

plt.show()

edges = cv2.Canny(img, 100, 200)
cv2.imwrite('output_edges.jpg', edges)

